-
  name: Deploy a web application
  hosts: db_and_web_servers
  tasks:
    - name: Install all required dependencies
      become: yes
      apt: name={{item}} state=present
      with_items:
        - python3
        - python3-setuptools
        - python3-dev
        - libffi-dev 
        - libssl-dev
        - build-essential
        - python3-pip
    
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml

    

    

    