-
    name: 'Update nameserver entry into resolv.conf file on localhost'
    hosts: all
    become: yes
    tasks:
        -
          name: 'Update nameserver entry into resolv.conf file'
          #need sudo permission  
          become: yes
          lineinfile:
              path: /etc/resolv.conf
              line: 'nameserver {{nameserver_ip}}'
        -
          name: 'Update hostname'                 
          hostname:
              name: '{{hostname}}'